default:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
  hystrix:
    enabled: true
hystrix:
  commond:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
  Socketimeout: 3000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
  redis:
    host: 127.0.0.1
    password: foobared
    port: 6379
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
