feign:
  client:
    config:
      default:
        connectTimeout: 4000
        loggerLevel: full
        readTimeout: 4000
hystrix:
  commond:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
  redis:
    host: 127.0.0.1
    password: foobared
    port: 6379
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
